#!/bin/bash

echo """
{+} Common CAN Identifiers

0x10 DiagnosticSessionControl
0x11 ECUReset
0x2E WriteDataByIdentifier
0x22 ReadDataByIdentifier
0x27 SecurityAccess
0x3E TesterPresent
0x31 RoutineControl
0x28 CommunicationControl
0x36 TransferData / 0x34 RequestDownload (file/flash transfer)
0x7F (negative response, sent by server)
"""